#pragma once

#ifndef STICKMON_ENABLE_DEBUG_FEATURES
#define STICKMON_ENABLE_DEBUG_FEATURES 0
#endif

#ifndef STICKMON_ENABLE_TRACE_LOGS
#define STICKMON_ENABLE_TRACE_LOGS 0
#endif

#ifndef STICKMON_ENABLE_RENDER_STATS
#define STICKMON_ENABLE_RENDER_STATS 0
#endif

#if STICKMON_ENABLE_DEBUG_FEATURES != 0 && STICKMON_ENABLE_DEBUG_FEATURES != 1
#error "STICKMON_ENABLE_DEBUG_FEATURES must be 0 or 1"
#endif

#if !STICKMON_ENABLE_DEBUG_FEATURES
#undef STICKMON_ENABLE_TRACE_LOGS
#define STICKMON_ENABLE_TRACE_LOGS 0
#undef STICKMON_ENABLE_RENDER_STATS
#define STICKMON_ENABLE_RENDER_STATS 0
#endif

namespace BuildConfig {
static constexpr bool DEBUG_FEATURES = STICKMON_ENABLE_DEBUG_FEATURES != 0;
}
