// AUTO-GENERATED by tools/generate_pokemon_sprites.py. Do not edit manually.
#include "assets/PokemonSprites.h"
#include "core/DeflateDecoder.h"
#include "core/MathUtil.h"
#include "core/ResourcePack.h"
#include <cstdlib>
#include <cstring>
#include "platform/api/FlashStorage.h"
#include "platform/api/PlatformServices.h"
#include "presentation/PixelRenderer.h"

namespace PokemonSprites {

namespace {

struct WalkingConfig {
    uint16_t speciesId;
    SpriteKind downBase;
    SpriteKind leftBase;
    SpriteKind upBase;
    SpriteKind rightBase;
    uint8_t frameCount;
    bool rightFlipX;
};

static constexpr WalkingConfig WALKING_CONFIGS[] = {
    {1, SpriteKind::BULBASAUR_WALKING_FRONT_0, SpriteKind::BULBASAUR_WALKING_LEFT_0, SpriteKind::BULBASAUR_WALKING_BACK_0, SpriteKind::BULBASAUR_WALKING_LEFT_0, 3, true},
    {2, SpriteKind::IVYSAUR_WALKING_FRONT_0, SpriteKind::IVYSAUR_WALKING_LEFT_0, SpriteKind::IVYSAUR_WALKING_BACK_0, SpriteKind::IVYSAUR_WALKING_LEFT_0, 3, true},
    {3, SpriteKind::VENUSAUR_WALKING_FRONT_0, SpriteKind::VENUSAUR_WALKING_LEFT_0, SpriteKind::VENUSAUR_WALKING_BACK_0, SpriteKind::VENUSAUR_WALKING_LEFT_0, 3, true},
    {4, SpriteKind::CHARMANDER_WALKING_FRONT_0, SpriteKind::CHARMANDER_WALKING_LEFT_0, SpriteKind::CHARMANDER_WALKING_BACK_0, SpriteKind::CHARMANDER_WALKING_LEFT_0, 3, true},
    {5, SpriteKind::CHARMELEON_WALKING_FRONT_0, SpriteKind::CHARMELEON_WALKING_LEFT_0, SpriteKind::CHARMELEON_WALKING_BACK_0, SpriteKind::CHARMELEON_WALKING_LEFT_0, 3, true},
    {6, SpriteKind::CHARIZARD_WALKING_FRONT_0, SpriteKind::CHARIZARD_WALKING_LEFT_0, SpriteKind::CHARIZARD_WALKING_BACK_0, SpriteKind::CHARIZARD_WALKING_LEFT_0, 3, true},
    {7, SpriteKind::SQUIRTLE_WALKING_FRONT_0, SpriteKind::SQUIRTLE_WALKING_LEFT_0, SpriteKind::SQUIRTLE_WALKING_BACK_0, SpriteKind::SQUIRTLE_WALKING_LEFT_0, 3, true},
    {8, SpriteKind::WARTORTLE_WALKING_FRONT_0, SpriteKind::WARTORTLE_WALKING_LEFT_0, SpriteKind::WARTORTLE_WALKING_BACK_0, SpriteKind::WARTORTLE_WALKING_RIGHT_0, 3, false},
    {9, SpriteKind::BLASTOISE_WALKING_FRONT_0, SpriteKind::BLASTOISE_WALKING_LEFT_0, SpriteKind::BLASTOISE_WALKING_BACK_0, SpriteKind::BLASTOISE_WALKING_LEFT_0, 3, true},
    {10, SpriteKind::CATERPIE_WALKING_FRONT_0, SpriteKind::CATERPIE_WALKING_LEFT_0, SpriteKind::CATERPIE_WALKING_BACK_0, SpriteKind::CATERPIE_WALKING_LEFT_0, 3, true},
    {11, SpriteKind::METAPOD_WALKING_FRONT_0, SpriteKind::METAPOD_WALKING_LEFT_0, SpriteKind::METAPOD_WALKING_BACK_0, SpriteKind::METAPOD_WALKING_LEFT_0, 3, true},
    {12, SpriteKind::BUTTERFREE_WALKING_FRONT_0, SpriteKind::BUTTERFREE_WALKING_LEFT_0, SpriteKind::BUTTERFREE_WALKING_BACK_0, SpriteKind::BUTTERFREE_WALKING_LEFT_0, 3, true},
    {16, SpriteKind::PIDGEY_WALKING_FRONT_0, SpriteKind::PIDGEY_WALKING_LEFT_0, SpriteKind::PIDGEY_WALKING_BACK_0, SpriteKind::PIDGEY_WALKING_LEFT_0, 3, true},
    {17, SpriteKind::PIDGEOTTO_WALKING_FRONT_0, SpriteKind::PIDGEOTTO_WALKING_LEFT_0, SpriteKind::PIDGEOTTO_WALKING_BACK_0, SpriteKind::PIDGEOTTO_WALKING_LEFT_0, 3, true},
    {18, SpriteKind::PIDGEOT_WALKING_FRONT_0, SpriteKind::PIDGEOT_WALKING_LEFT_0, SpriteKind::PIDGEOT_WALKING_BACK_0, SpriteKind::PIDGEOT_WALKING_LEFT_0, 3, true},
    {25, SpriteKind::PIKACHU_WALKING_FRONT_0, SpriteKind::PIKACHU_WALKING_LEFT_0, SpriteKind::PIKACHU_WALKING_BACK_0, SpriteKind::PIKACHU_WALKING_LEFT_0, 3, true},
    {26, SpriteKind::RAICHU_WALKING_FRONT_0, SpriteKind::RAICHU_WALKING_LEFT_0, SpriteKind::RAICHU_WALKING_BACK_0, SpriteKind::RAICHU_WALKING_RIGHT_0, 3, false},
    {74, SpriteKind::GEODUDE_WALKING_FRONT_0, SpriteKind::GEODUDE_WALKING_LEFT_0, SpriteKind::GEODUDE_WALKING_BACK_0, SpriteKind::GEODUDE_WALKING_LEFT_0, 3, true},
    {75, SpriteKind::GRAVELER_WALKING_FRONT_0, SpriteKind::GRAVELER_WALKING_LEFT_0, SpriteKind::GRAVELER_WALKING_BACK_0, SpriteKind::GRAVELER_WALKING_LEFT_0, 3, true},
    {76, SpriteKind::GOLEM_WALKING_FRONT_0, SpriteKind::GOLEM_WALKING_LEFT_0, SpriteKind::GOLEM_WALKING_BACK_0, SpriteKind::GOLEM_WALKING_LEFT_0, 3, true},
    {92, SpriteKind::GASTLY_WALKING_FRONT_0, SpriteKind::GASTLY_WALKING_LEFT_0, SpriteKind::GASTLY_WALKING_BACK_0, SpriteKind::GASTLY_WALKING_LEFT_0, 3, true},
    {93, SpriteKind::HAUNTER_WALKING_FRONT_0, SpriteKind::HAUNTER_WALKING_LEFT_0, SpriteKind::HAUNTER_WALKING_BACK_0, SpriteKind::HAUNTER_WALKING_LEFT_0, 3, true},
    {94, SpriteKind::GENGAR_WALKING_FRONT_0, SpriteKind::GENGAR_WALKING_LEFT_0, SpriteKind::GENGAR_WALKING_BACK_0, SpriteKind::GENGAR_WALKING_LEFT_0, 3, true},
    {123, SpriteKind::SCYTHER_WALKING_FRONT_0, SpriteKind::SCYTHER_WALKING_LEFT_0, SpriteKind::SCYTHER_WALKING_BACK_0, SpriteKind::SCYTHER_WALKING_LEFT_0, 3, true},
    {129, SpriteKind::MAGIKARP_WALKING_FRONT_0, SpriteKind::MAGIKARP_WALKING_LEFT_0, SpriteKind::MAGIKARP_WALKING_BACK_0, SpriteKind::MAGIKARP_WALKING_RIGHT_0, 1, false},
    {130, SpriteKind::GYARADOS_WALKING_FRONT_0, SpriteKind::GYARADOS_WALKING_LEFT_0, SpriteKind::GYARADOS_WALKING_BACK_0, SpriteKind::GYARADOS_WALKING_RIGHT_0, 3, false},
    {133, SpriteKind::EEVEE_WALKING_FRONT_0, SpriteKind::EEVEE_WALKING_LEFT_0, SpriteKind::EEVEE_WALKING_BACK_0, SpriteKind::EEVEE_WALKING_RIGHT_0, 3, false},
    {134, SpriteKind::VAPOREON_WALKING_FRONT_0, SpriteKind::VAPOREON_WALKING_LEFT_0, SpriteKind::VAPOREON_WALKING_BACK_0, SpriteKind::VAPOREON_WALKING_RIGHT_0, 4, false},
    {135, SpriteKind::JOLTEON_WALKING_FRONT_0, SpriteKind::JOLTEON_WALKING_LEFT_0, SpriteKind::JOLTEON_WALKING_BACK_0, SpriteKind::JOLTEON_WALKING_RIGHT_0, 4, false},
    {136, SpriteKind::FLAREON_WALKING_FRONT_0, SpriteKind::FLAREON_WALKING_LEFT_0, SpriteKind::FLAREON_WALKING_BACK_0, SpriteKind::FLAREON_WALKING_RIGHT_0, 4, false},
    {196, SpriteKind::ESPEON_WALKING_FRONT_0, SpriteKind::ESPEON_WALKING_LEFT_0, SpriteKind::ESPEON_WALKING_BACK_0, SpriteKind::ESPEON_WALKING_LEFT_0, 3, true},
    {197, SpriteKind::UMBREON_WALKING_FRONT_0, SpriteKind::UMBREON_WALKING_LEFT_0, SpriteKind::UMBREON_WALKING_BACK_0, SpriteKind::UMBREON_WALKING_LEFT_0, 3, true},
    {143, SpriteKind::SNORLAX_WALKING_FRONT_0, SpriteKind::SNORLAX_WALKING_LEFT_0, SpriteKind::SNORLAX_WALKING_BACK_0, SpriteKind::SNORLAX_WALKING_LEFT_0, 3, true},
    {147, SpriteKind::DRATINI_WALKING_FRONT_0, SpriteKind::DRATINI_WALKING_LEFT_0, SpriteKind::DRATINI_WALKING_BACK_0, SpriteKind::DRATINI_WALKING_RIGHT_0, 3, false},
    {148, SpriteKind::DRAGONAIR_WALKING_FRONT_0, SpriteKind::DRAGONAIR_WALKING_LEFT_0, SpriteKind::DRAGONAIR_WALKING_BACK_0, SpriteKind::DRAGONAIR_WALKING_RIGHT_0, 3, false},
    {149, SpriteKind::DRAGONITE_WALKING_FRONT_0, SpriteKind::DRAGONITE_WALKING_LEFT_0, SpriteKind::DRAGONITE_WALKING_BACK_0, SpriteKind::DRAGONITE_WALKING_RIGHT_0, 2, false},
    {151, SpriteKind::MEW_WALKING_FRONT_0, SpriteKind::MEW_WALKING_LEFT_0, SpriteKind::MEW_WALKING_BACK_0, SpriteKind::MEW_WALKING_RIGHT_0, 2, false},
    {161, SpriteKind::SENTRET_WALKING_FRONT_0, SpriteKind::SENTRET_WALKING_LEFT_0, SpriteKind::SENTRET_WALKING_BACK_0, SpriteKind::SENTRET_WALKING_LEFT_0, 3, true},
    {162, SpriteKind::FURRET_WALKING_FRONT_0, SpriteKind::FURRET_WALKING_LEFT_0, SpriteKind::FURRET_WALKING_BACK_0, SpriteKind::FURRET_WALKING_LEFT_0, 3, true},
    {172, SpriteKind::PICHU_WALKING_FRONT_0, SpriteKind::PICHU_WALKING_LEFT_0, SpriteKind::PICHU_WALKING_BACK_0, SpriteKind::PICHU_WALKING_LEFT_0, 3, true},
    {183, SpriteKind::MARILL_WALKING_FRONT_0, SpriteKind::MARILL_WALKING_LEFT_0, SpriteKind::MARILL_WALKING_BACK_0, SpriteKind::MARILL_WALKING_LEFT_0, 3, true},
    {184, SpriteKind::AZUMARILL_WALKING_FRONT_0, SpriteKind::AZUMARILL_WALKING_LEFT_0, SpriteKind::AZUMARILL_WALKING_BACK_0, SpriteKind::AZUMARILL_WALKING_LEFT_0, 3, true},
    {194, SpriteKind::WOOPER_WALKING_FRONT_0, SpriteKind::WOOPER_WALKING_LEFT_0, SpriteKind::WOOPER_WALKING_BACK_0, SpriteKind::WOOPER_WALKING_LEFT_0, 3, true},
    {195, SpriteKind::QUAGSIRE_WALKING_FRONT_0, SpriteKind::QUAGSIRE_WALKING_LEFT_0, SpriteKind::QUAGSIRE_WALKING_BACK_0, SpriteKind::QUAGSIRE_WALKING_LEFT_0, 2, true},
    {212, SpriteKind::SCIZOR_WALKING_FRONT_0, SpriteKind::SCIZOR_WALKING_LEFT_0, SpriteKind::SCIZOR_WALKING_BACK_0, SpriteKind::SCIZOR_WALKING_LEFT_0, 3, true},
    {261, SpriteKind::POOCHYENA_WALKING_FRONT_0, SpriteKind::POOCHYENA_WALKING_LEFT_0, SpriteKind::POOCHYENA_WALKING_BACK_0, SpriteKind::POOCHYENA_WALKING_LEFT_0, 3, true},
    {262, SpriteKind::MIGHTYENA_WALKING_FRONT_0, SpriteKind::MIGHTYENA_WALKING_LEFT_0, SpriteKind::MIGHTYENA_WALKING_BACK_0, SpriteKind::MIGHTYENA_WALKING_LEFT_0, 3, true},
    {278, SpriteKind::WINGULL_WALKING_FRONT_0, SpriteKind::WINGULL_WALKING_LEFT_0, SpriteKind::WINGULL_WALKING_BACK_0, SpriteKind::WINGULL_WALKING_LEFT_0, 3, true},
    {279, SpriteKind::PELIPPER_WALKING_FRONT_0, SpriteKind::PELIPPER_WALKING_LEFT_0, SpriteKind::PELIPPER_WALKING_BACK_0, SpriteKind::PELIPPER_WALKING_LEFT_0, 3, true},
    {285, SpriteKind::SHROOMISH_WALKING_FRONT_0, SpriteKind::SHROOMISH_WALKING_LEFT_0, SpriteKind::SHROOMISH_WALKING_BACK_0, SpriteKind::SHROOMISH_WALKING_LEFT_0, 3, true},
    {286, SpriteKind::BRELOOM_WALKING_FRONT_0, SpriteKind::BRELOOM_WALKING_LEFT_0, SpriteKind::BRELOOM_WALKING_BACK_0, SpriteKind::BRELOOM_WALKING_LEFT_0, 3, true},
    {380, SpriteKind::LATIAS_WALKING_FRONT_0, SpriteKind::LATIAS_WALKING_LEFT_0, SpriteKind::LATIAS_WALKING_BACK_0, SpriteKind::LATIAS_WALKING_LEFT_0, 2, true},
    {381, SpriteKind::LATIOS_WALKING_FRONT_0, SpriteKind::LATIOS_WALKING_LEFT_0, SpriteKind::LATIOS_WALKING_BACK_0, SpriteKind::LATIOS_WALKING_LEFT_0, 2, true},
    {298, SpriteKind::AZURILL_WALKING_FRONT_0, SpriteKind::AZURILL_WALKING_LEFT_0, SpriteKind::AZURILL_WALKING_BACK_0, SpriteKind::AZURILL_WALKING_LEFT_0, 3, true},
    {322, SpriteKind::NUMEL_WALKING_FRONT_0, SpriteKind::NUMEL_WALKING_LEFT_0, SpriteKind::NUMEL_WALKING_BACK_0, SpriteKind::NUMEL_WALKING_LEFT_0, 3, true},
    {323, SpriteKind::CAMERUPT_WALKING_FRONT_0, SpriteKind::CAMERUPT_WALKING_LEFT_0, SpriteKind::CAMERUPT_WALKING_BACK_0, SpriteKind::CAMERUPT_WALKING_LEFT_0, 3, true},
    {361, SpriteKind::SNORUNT_WALKING_FRONT_0, SpriteKind::SNORUNT_WALKING_LEFT_0, SpriteKind::SNORUNT_WALKING_BACK_0, SpriteKind::SNORUNT_WALKING_LEFT_0, 4, true},
    {362, SpriteKind::GLALIE_WALKING_FRONT_0, SpriteKind::GLALIE_WALKING_LEFT_0, SpriteKind::GLALIE_WALKING_BACK_0, SpriteKind::GLALIE_WALKING_LEFT_0, 1, true},
    {280, SpriteKind::RALTS_WALKING_FRONT_0, SpriteKind::RALTS_WALKING_LEFT_0, SpriteKind::RALTS_WALKING_BACK_0, SpriteKind::RALTS_WALKING_LEFT_0, 3, true},
    {281, SpriteKind::KIRLIA_WALKING_FRONT_0, SpriteKind::KIRLIA_WALKING_LEFT_0, SpriteKind::KIRLIA_WALKING_BACK_0, SpriteKind::KIRLIA_WALKING_LEFT_0, 2, true},
    {282, SpriteKind::GARDEVOIR_WALKING_FRONT_0, SpriteKind::GARDEVOIR_WALKING_LEFT_0, SpriteKind::GARDEVOIR_WALKING_BACK_0, SpriteKind::GARDEVOIR_WALKING_LEFT_0, 3, true},
    {41, SpriteKind::ZUBAT_WALKING_FRONT_0, SpriteKind::ZUBAT_WALKING_LEFT_0, SpriteKind::ZUBAT_WALKING_BACK_0, SpriteKind::ZUBAT_WALKING_LEFT_0, 3, true},
    {42, SpriteKind::GOLBAT_WALKING_FRONT_0, SpriteKind::GOLBAT_WALKING_LEFT_0, SpriteKind::GOLBAT_WALKING_BACK_0, SpriteKind::GOLBAT_WALKING_LEFT_0, 3, true},
    {169, SpriteKind::CROBAT_WALKING_FRONT_0, SpriteKind::CROBAT_WALKING_LEFT_0, SpriteKind::CROBAT_WALKING_BACK_0, SpriteKind::CROBAT_WALKING_LEFT_0, 3, true},
};

static constexpr uint8_t SPRITE_SOURCE_FILE_BLOCK = 2;
static constexpr uint16_t SPRITE_FRAME_GROUND_MARKER = 0xA500;
static constexpr uint8_t TEAM_CACHE_CAP = 2;
static constexpr uint8_t EXPLORE_PINNED_CACHE_CAP = 36;
static constexpr uint8_t TRANSIENT_CACHE_CAP = 4;
static constexpr uint8_t DYNAMIC_CACHE_CAP =
    EXPLORE_PINNED_CACHE_CAP + TRANSIENT_CACHE_CAP;
static constexpr uint8_t CACHE_CAP = TEAM_CACHE_CAP + DYNAMIC_CACHE_CAP;
static constexpr uint8_t SCENE_SPECIES_CAP = 6;
static constexpr uint8_t KNOWN_MISSING_FILE_CAP = 16;
static constexpr uint8_t FRAME_MISSING_CAP = 4;
static constexpr uint8_t KNOWN_MISSING_FRAME_CAP = 16;
static constexpr uint32_t SPRITE_PACK_MAGIC = 0x5350534D;
static constexpr uint16_t SPRITE_PACK_VERSION = 2;
static constexpr uint16_t SPRITE_PACK_FLAG_RAW_DEFLATE = 1;
static constexpr uint16_t MAX_PACK_FRAMES = 256;
static constexpr uint32_t MAX_PACK_PAYLOAD_BYTES = 128000;

struct __attribute__((packed)) PackedSpriteHeader {
    uint32_t magic;
    uint16_t version;
    uint16_t speciesId;
    uint16_t frameCount;
    uint16_t rleWords;
    uint16_t paletteWords;
    uint16_t flags;
    uint32_t payloadRawBytes;
    uint32_t payloadCompressedBytes;
    uint32_t payloadCrc32;
};

struct __attribute__((packed)) PackedSpriteFrame {
    uint16_t kind;
    uint8_t width;
    uint8_t height;
    uint8_t format;
    uint8_t paletteSize;
    uint16_t reserved;
    uint32_t offset;
    uint32_t length;
    uint32_t paletteOffset;
};

static_assert(sizeof(PackedSpriteHeader) == 28, "Unexpected sprite pack header layout");
static_assert(sizeof(PackedSpriteFrame) == 20, "Unexpected sprite pack frame layout");

struct CachedSpecies {
    uint16_t speciesId = 0;
    uint16_t rleWords = 0;
    uint16_t paletteWords = 0;
    uint16_t frameCount = 0;
    SpriteFrame* frames = nullptr;
    uint8_t* payload = nullptr;
    uint32_t payloadBytes = 0;
    uint32_t packedBytes = 0;
    uint16_t* data = nullptr;
    uint16_t* palettes = nullptr;
    uint32_t lastUsed = 0;
};

struct MissingFrameKey {
    uint16_t speciesId = 0;
    uint16_t kind = 0;
};

CachedSpecies gCache[CACHE_CAP];
SpriteCacheStats gStats = {};
uint16_t gTeamSignature[TEAM_CACHE_CAP] = {};
uint16_t gKnownMissingFiles[KNOWN_MISSING_FILE_CAP] = {};
uint16_t gTeamMissing[TEAM_CACHE_CAP] = {};
uint16_t gFrameMissing[FRAME_MISSING_CAP] = {};
MissingFrameKey gKnownMissingFrames[KNOWN_MISSING_FRAME_CAP] = {};
uint8_t gTeamCount = 0;
uint16_t gSceneSpecies[SCENE_SPECIES_CAP] = {};
uint8_t gSceneSpeciesCount = 0;
uint16_t gPinnedSpecies[EXPLORE_PINNED_CACHE_CAP] = {};
uint8_t gPinnedSpeciesCount = 0;
uint32_t gUseSerial = 0;
bool gDynamicLoadingEnabled = true;

bool containsSpecies(const uint16_t* values, uint8_t count, uint16_t speciesId) {
    for (uint8_t i = 0; i < count; ++i) {
        if (values[i] == speciesId) return true;
    }
    return false;
}

bool appendUniqueSpecies(uint16_t* values, uint8_t count, uint16_t speciesId) {
    if (speciesId == 0 || containsSpecies(values, count, speciesId)) return false;
    for (uint8_t i = 0; i < count; ++i) {
        if (values[i] == 0) {
            values[i] = speciesId;
            return true;
        }
    }
    return false;
}

void refreshMissingStats() {
    uint16_t unique[TEAM_CACHE_CAP + FRAME_MISSING_CAP] = {};
    uint8_t uniqueCount = 0;
    auto collect = [&](const uint16_t* values, uint8_t count) {
        for (uint8_t i = 0; i < count; ++i) {
            uint16_t speciesId = values[i];
            if (speciesId == 0 || containsSpecies(unique, uniqueCount, speciesId)) continue;
            unique[uniqueCount++] = speciesId;
        }
    };
    collect(gTeamMissing, TEAM_CACHE_CAP);
    collect(gFrameMissing, FRAME_MISSING_CAP);
    gStats.missingSpecies = uniqueCount;
    gStats.firstMissingSpecies = uniqueCount > 0 ? unique[0] : 0;
}

void noteMissingSpecies(uint16_t speciesId) {
    if (speciesId == 0) return;
    bool teamSpecies = false;
    for (uint8_t i = 0; i < gTeamCount; ++i) {
        if (gTeamSignature[i] == speciesId) {
            gTeamMissing[i] = speciesId;
            teamSpecies = true;
        }
    }
    if (!teamSpecies) appendUniqueSpecies(gFrameMissing, FRAME_MISSING_CAP, speciesId);
    refreshMissingStats();
}

void releaseEntry(CachedSpecies& entry) {
    if (entry.payload) {
        uint32_t decodedBytes = entry.payloadBytes +
                                static_cast<uint32_t>(entry.frameCount) * sizeof(SpriteFrame);
        gStats.decodedBytes = gStats.decodedBytes >= decodedBytes
            ? gStats.decodedBytes - decodedBytes : 0;
        gStats.compressedBytes = gStats.compressedBytes >= entry.packedBytes
            ? gStats.compressedBytes - entry.packedBytes : 0;
        if (gStats.cachedSpecies > 0) --gStats.cachedSpecies;
        Platform::memory().release(entry.payload);
    }
    if (entry.frames) Platform::memory().release(entry.frames);
    entry = CachedSpecies{};
}

void freeCache() {
    for (auto& entry : gCache) {
        releaseEntry(entry);
    }
    uint32_t reloadCount = gStats.reloadCount;
    gStats = SpriteCacheStats{};
    gStats.reloadCount = reloadCount;
    gStats.cachedSpecies = 0;
    gStats.freePsram = Platform::memory().externalFree();
    gStats.psram = Platform::power().externalMemorySize() > 0;
    memset(gKnownMissingFiles, 0, sizeof(gKnownMissingFiles));
    memset(gTeamSignature, 0, sizeof(gTeamSignature));
    memset(gTeamMissing, 0, sizeof(gTeamMissing));
    memset(gFrameMissing, 0, sizeof(gFrameMissing));
    memset(gKnownMissingFrames, 0, sizeof(gKnownMissingFrames));
    memset(gSceneSpecies, 0, sizeof(gSceneSpecies));
    gSceneSpeciesCount = 0;
    memset(gPinnedSpecies, 0, sizeof(gPinnedSpecies));
    gTeamCount = 0;
    gPinnedSpeciesCount = 0;
    gUseSerial = 0;
}

bool knownMissingFile(uint16_t speciesId) {
    if (speciesId == 0) return true;
    for (uint8_t i = 0; i < KNOWN_MISSING_FILE_CAP; ++i) {
        if (gKnownMissingFiles[i] == speciesId) return true;
    }
    return false;
}

bool rememberMissingFile(uint16_t speciesId) {
    if (speciesId == 0 || knownMissingFile(speciesId)) return false;
    for (uint8_t i = 0; i < KNOWN_MISSING_FILE_CAP; ++i) {
        if (gKnownMissingFiles[i] == 0) {
            gKnownMissingFiles[i] = speciesId;
            return true;
        }
    }
    return false;
}

bool rememberMissingFrame(uint16_t speciesId, uint16_t kind) {
    for (uint8_t i = 0; i < KNOWN_MISSING_FRAME_CAP; ++i) {
        const MissingFrameKey& key = gKnownMissingFrames[i];
        if (key.speciesId == speciesId && key.kind == kind) return false;
        if (key.speciesId == 0) {
            gKnownMissingFrames[i].speciesId = speciesId;
            gKnownMissingFrames[i].kind = kind;
            return true;
        }
    }
    return false;
}

void touchEntry(CachedSpecies& entry) {
    if (entry.speciesId == 0) return;
    ++gUseSerial;
    if (gUseSerial == 0) gUseSerial = 1;
    entry.lastUsed = gUseSerial;
}

CachedSpecies* cachedSpeciesFor(uint16_t speciesId, bool touch = true) {
    for (auto& entry : gCache) {
        if (entry.speciesId == speciesId && entry.data) {
            if (touch) touchEntry(entry);
            return &entry;
        }
    }
    return nullptr;
}

bool readExact(Platform::ResourceFile& file, void* out, size_t length) {
    if (length == 0) return true;
    return file.read(reinterpret_cast<uint8_t*>(out), length) == length;
}

bool validPackedFrame(const PackedSpriteFrame& frame, const PackedSpriteHeader& header) {
    if (frame.width == 0 || frame.height == 0 || frame.length == 0) return false;
    if (frame.format != static_cast<uint8_t>(SpriteFormat::RGB565_RLE) &&
        frame.format != static_cast<uint8_t>(SpriteFormat::INDEXED4_RLE)) {
        return false;
    }
    if (frame.offset > header.rleWords || frame.length > header.rleWords - frame.offset) return false;
    if (frame.format == static_cast<uint8_t>(SpriteFormat::INDEXED4_RLE)) {
        if (frame.paletteSize == 0 || frame.paletteSize > 16) return false;
        if (frame.paletteOffset > header.paletteWords ||
            frame.paletteSize > header.paletteWords - frame.paletteOffset) {
            return false;
        }
    }
    return true;
}

bool loadSpeciesFromResourcePack(uint8_t slot, uint16_t speciesId) {
    ResourcePack& pack = ResourcePack::ins();
    if (!pack.begin()) return false;

    Platform::ResourceFile file;
    if (!pack.openSpriteBlock(speciesId, file)) return false;

    PackedSpriteHeader header = {};
    if (!readExact(file, &header, sizeof(header))) return false;
    if (header.magic != SPRITE_PACK_MAGIC ||
        header.version != SPRITE_PACK_VERSION ||
        header.speciesId != speciesId ||
        header.frameCount == 0 ||
        header.frameCount > MAX_PACK_FRAMES ||
        header.rleWords == 0 ||
        header.flags != SPRITE_PACK_FLAG_RAW_DEFLATE ||
        header.payloadRawBytes == 0 ||
        header.payloadRawBytes > MAX_PACK_PAYLOAD_BYTES ||
        header.payloadCompressedBytes == 0) {
        return false;
    }

    uint32_t frameBytes = static_cast<uint32_t>(header.frameCount) * sizeof(SpriteFrame);
    uint32_t packedFrameBytes = static_cast<uint32_t>(header.frameCount) * sizeof(PackedSpriteFrame);
    uint32_t expectedPayloadBytes = packedFrameBytes +
        (static_cast<uint32_t>(header.rleWords) + header.paletteWords) * sizeof(uint16_t);
    uint32_t fileBytes = static_cast<uint32_t>(file.size());
    if (expectedPayloadBytes != header.payloadRawBytes ||
        static_cast<uint64_t>(sizeof(PackedSpriteHeader)) + header.payloadCompressedBytes != file.size()) {
        return false;
    }

    SpriteFrame* frames = static_cast<SpriteFrame*>(
        Platform::memory().allocate(frameBytes, true));
    uint8_t* payload = static_cast<uint8_t*>(
        Platform::memory().allocate(header.payloadRawBytes, true));
    if (!frames || !payload) {
        if (frames) Platform::memory().release(frames);
        if (payload) Platform::memory().release(payload);
        return false;
    }

    DeflateDecoder::Stats decodeStats{};
    if (!DeflateDecoder::inflateFile(file,
                                     header.payloadCompressedBytes,
                                     payload,
                                     header.payloadRawBytes,
                                     header.payloadCrc32,
                                     &decodeStats)) {
        Platform::memory().release(frames);
        Platform::memory().release(payload);
        Platform::logf(
            "[PokemonSprites] decode failed species=%u read=%u inflate=%u total=%u\n",
            speciesId, decodeStats.readMs, decodeStats.inflateMs, decodeStats.totalMs);
        return false;
    }

    const auto* packedFrames = reinterpret_cast<const PackedSpriteFrame*>(payload);
    for (uint16_t i = 0; i < header.frameCount; ++i) {
        const PackedSpriteFrame& packed = packedFrames[i];
        if (!validPackedFrame(packed, header)) {
            Platform::memory().release(frames);
            Platform::memory().release(payload);
            return false;
        }
        frames[i] = SpriteFrame{
            speciesId,
            packed.kind,
            packed.width,
            packed.height,
            packed.format,
            packed.paletteSize,
            SPRITE_SOURCE_FILE_BLOCK,
            static_cast<uint8_t>(
                (packed.reserved & 0xFF00U) == SPRITE_FRAME_GROUND_MARKER
                    ? (packed.reserved & 0x00FFU) + 1U
                    : 0U),
            packed.offset,
            packed.length,
            packed.paletteOffset,
        };
    }

    uint16_t* decoded = reinterpret_cast<uint16_t*>(payload + packedFrameBytes);

    CachedSpecies& entry = gCache[slot];
    releaseEntry(entry);
    entry.speciesId = speciesId;
    entry.rleWords = header.rleWords;
    entry.paletteWords = header.paletteWords;
    entry.frameCount = header.frameCount;
    entry.frames = frames;
    entry.payload = payload;
    entry.payloadBytes = header.payloadRawBytes;
    entry.packedBytes = fileBytes;
    entry.data = decoded;
    entry.palettes = decoded + header.rleWords;
    touchEntry(entry);

    if (gStats.cachedSpecies < 0xFF) ++gStats.cachedSpecies;
    gStats.decodedBytes += header.payloadRawBytes + frameBytes;
    gStats.compressedBytes += fileBytes;
    Platform::logf(
        "[PokemonSprites] source=littlefs species=%u frames=%u compressed=%u decoded=%u read=%u inflate=%u total=%u\n",
        speciesId, header.frameCount, fileBytes, header.payloadRawBytes + frameBytes,
        decodeStats.readMs, decodeStats.inflateMs, decodeStats.totalMs);
    return true;
}

bool loadSpeciesIntoCache(uint8_t slot, uint16_t speciesId) {
    if (slot >= CACHE_CAP || speciesId == 0) return false;
    if (loadSpeciesFromResourcePack(slot, speciesId)) {
        if (slot < TEAM_CACHE_CAP) gTeamMissing[slot] = 0;
        refreshMissingStats();
        return true;
    }
    noteMissingSpecies(speciesId);
    if (rememberMissingFile(speciesId)) {
        Platform::logf("[PokemonSprites] missing species=%u\n", speciesId);
    }
    return false;
}

uint8_t dynamicCacheSlot(const uint16_t* protectedSpecies = nullptr,
                         uint8_t protectedCount = 0) {
    for (uint8_t i = TEAM_CACHE_CAP; i < CACHE_CAP; ++i) {
        if (gCache[i].speciesId == 0) return i;
    }

    uint8_t oldestSlot = CACHE_CAP;
    uint32_t oldestUse = UINT32_MAX;
    for (uint8_t i = TEAM_CACHE_CAP; i < CACHE_CAP; ++i) {
        uint16_t speciesId = gCache[i].speciesId;
        if (containsSpecies(gSceneSpecies, gSceneSpeciesCount, speciesId) ||
            containsSpecies(gPinnedSpecies, gPinnedSpeciesCount, speciesId) ||
            containsSpecies(protectedSpecies, protectedCount, speciesId)) {
            continue;
        }
        if (oldestSlot == CACHE_CAP || gCache[i].lastUsed < oldestUse) {
            oldestSlot = i;
            oldestUse = gCache[i].lastUsed;
        }
    }
    return oldestSlot;
}

CachedSpecies* ensureSpeciesLoaded(uint16_t speciesId) {
    CachedSpecies* cached = cachedSpeciesFor(speciesId);
    if (cached) return cached;
    if (!gDynamicLoadingEnabled) return nullptr;
    if (knownMissingFile(speciesId)) {
        noteMissingSpecies(speciesId);
        return nullptr;
    }

    uint8_t slot = dynamicCacheSlot();
    if (slot >= CACHE_CAP) return nullptr;
    if (!loadSpeciesIntoCache(slot, speciesId)) return nullptr;
    return cachedSpeciesFor(speciesId);
}

const SpriteFrame* findFrame(CachedSpecies* cached, SpriteKind kind) {
    if (!cached || !cached->frames) return nullptr;
    uint16_t wantedKind = static_cast<uint16_t>(kind);
    for (uint16_t i = 0; i < cached->frameCount; ++i) {
        if (cached->frames[i].kind == wantedKind) return &cached->frames[i];
    }
    return nullptr;
}
}


bool walkingAnimation(uint16_t speciesId, WalkDirection direction, WalkingAnimation& animation) {
    for (const auto& config : WALKING_CONFIGS) {
        if (config.speciesId != speciesId) continue;
        animation.frameCount = config.frameCount;
        animation.flipX = false;
        switch (direction) {
        case WalkDirection::DOWN: animation.base = config.downBase; break;
        case WalkDirection::LEFT: animation.base = config.leftBase; break;
        case WalkDirection::UP: animation.base = config.upBase; break;
        case WalkDirection::RIGHT:
            animation.base = config.rightBase;
            animation.flipX = config.rightFlipX;
            break;
        }
        return animation.frameCount > 0;
    }
    return false;
}

const SpriteFrame* findSpeciesSprite(uint16_t speciesId, SpriteKind kind) {
    CachedSpecies* cached = ensureSpeciesLoaded(speciesId);
    const SpriteFrame* frame = findFrame(cached, kind);
    if (frame) return frame;
    if (!cached || speciesId == 0) return nullptr;
    noteMissingSpecies(speciesId);
    uint16_t kindValue = static_cast<uint16_t>(kind);
    if (rememberMissingFrame(speciesId, kindValue)) {
        Platform::logf("[PokemonSprites] missing frame species=%u kind=%u\n",
                      speciesId, static_cast<unsigned>(kindValue));
    }
    return nullptr;
}

const SpriteFrame* findCachedSpeciesSprite(uint16_t speciesId, SpriteKind kind) {
    return findFrame(cachedSpeciesFor(speciesId), kind);
}

int16_t frameGroundOffsetY(const SpriteFrame* frame) {
    if (!frame) return 0;
    uint8_t height = FlashStorage::readByte(&frame->height);
    uint8_t encodedPadding = FlashStorage::readByte(&frame->groundPaddingPlusOne);
    if (encodedPadding > 0) {
        int bottomPadding = encodedPadding - 1;
        return static_cast<int16_t>(height / 2 - bottomPadding);
    }
    return static_cast<int16_t>(MathUtil::clamp((int)(height * 0.42f), 16, 32));
}

bool syncTeamCache(const uint16_t* speciesIds, uint8_t count,
                   uint8_t loadBudget, bool* cacheChanged) {
    if (cacheChanged) *cacheChanged = false;
    if (!speciesIds) count = 0;
    if (count > TEAM_CACHE_CAP) count = TEAM_CACHE_CAP;

    uint16_t next[TEAM_CACHE_CAP] = {};
    for (uint8_t i = 0; i < count; ++i) next[i] = speciesIds[i];
    bool signatureChanged = count != gTeamCount;
    if (count == gTeamCount) {
        for (uint8_t i = 0; i < TEAM_CACHE_CAP; ++i) {
            if (next[i] != gTeamSignature[i]) {
                signatureChanged = true;
                break;
            }
        }
    }

    uint32_t start = Platform::clock().millis();
    bool changed = signatureChanged;
    if (signatureChanged) {
        for (uint8_t i = 0; i < TEAM_CACHE_CAP; ++i) {
            uint16_t oldSpecies = gCache[i].speciesId;
            bool keep = oldSpecies != 0 &&
                (containsSpecies(next, count, oldSpecies) ||
                 containsSpecies(
                     gPinnedSpecies, gPinnedSpeciesCount, oldSpecies));
            if (keep) {
                uint8_t slot = dynamicCacheSlot(next, count);
                if (slot < CACHE_CAP) {
                    if (gCache[slot].speciesId != 0) releaseEntry(gCache[slot]);
                    gCache[slot] = gCache[i];
                    gCache[i] = CachedSpecies{};
                } else {
                    releaseEntry(gCache[i]);
                }
            } else {
                releaseEntry(gCache[i]);
            }
        }
        memset(gTeamMissing, 0, sizeof(gTeamMissing));
        gTeamCount = count;
        for (uint8_t i = 0; i < TEAM_CACHE_CAP; ++i) {
            gTeamSignature[i] = next[i];
        }
        ++gStats.reloadCount;
    }

    uint8_t loadedThisCall = 0;
    uint8_t movedThisCall = 0;
    for (uint8_t i = 0; i < count; ++i) {
        if (next[i] == 0 || gCache[i].speciesId == next[i]) continue;
        CachedSpecies* cached = cachedSpeciesFor(next[i], false);
        if (cached && cached >= &gCache[TEAM_CACHE_CAP]) {
            gCache[i] = *cached;
            *cached = CachedSpecies{};
            touchEntry(gCache[i]);
            ++movedThisCall;
            continue;
        }
        if (loadedThisCall >= loadBudget) continue;
        if (!loadSpeciesIntoCache(i, next[i])) {
            Platform::logf("[PokemonSprites] cache miss species=%u\n", next[i]);
        } else {
            changed = true;
        }
        ++loadedThisCall;
    }

    bool ready = true;
    for (uint8_t i = 0; i < count; ++i) {
        if (next[i] != 0 && gCache[i].speciesId != next[i]) {
            ready = false;
            break;
        }
    }
    changed = changed || movedThisCall > 0;
    if (cacheChanged) *cacheChanged = changed;
    if (!changed && loadedThisCall == 0) return ready;

    gStats.lastReloadMs = Platform::clock().millis() - start;
    gStats.freePsram = Platform::memory().externalFree();
    gStats.psram = Platform::power().externalMemorySize() > 0;
    Platform::logf(
        "[PokemonSprites] cache sync species=%u,%u loaded=%u moved=%u ready=%u cached=%u missing=%u decoded=%u compressed=%u ms=%u psram=%u free=%u\n",
        gTeamSignature[0], gTeamSignature[1], loadedThisCall, movedThisCall,
        ready ? 1 : 0,
        gStats.cachedSpecies, gStats.missingSpecies,
        gStats.decodedBytes, gStats.compressedBytes, gStats.lastReloadMs,
        gStats.psram ? 1 : 0, gStats.freePsram);
    return ready;
}

bool preloadDynamicSpecies(const uint16_t* speciesIds, uint8_t count,
                           uint8_t loadBudget) {
    if (!speciesIds) count = 0;
    if (count > DYNAMIC_CACHE_CAP) count = DYNAMIC_CACHE_CAP;

    uint16_t requested[DYNAMIC_CACHE_CAP] = {};
    uint8_t requestedCount = 0;
    for (uint8_t i = 0; i < count; ++i) {
        uint16_t speciesId = speciesIds[i];
        if (speciesId == 0 ||
            containsSpecies(requested, requestedCount, speciesId)) {
            continue;
        }
        requested[requestedCount++] = speciesId;
    }

    uint32_t start = Platform::clock().millis();
    uint8_t loadAttempts = 0;
    uint8_t evicted = 0;
    for (uint8_t i = 0; i < requestedCount; ++i) {
        uint16_t speciesId = requested[i];
        if (cachedSpeciesFor(speciesId, false) || knownMissingFile(speciesId)) continue;
        if (loadAttempts >= loadBudget) continue;
        uint8_t slot = dynamicCacheSlot(requested, requestedCount);
        if (slot >= CACHE_CAP) continue;
        if (gCache[slot].speciesId != 0) ++evicted;
        ++loadAttempts;
        loadSpeciesIntoCache(slot, speciesId);
    }

    bool ready = true;
    for (uint8_t i = 0; i < requestedCount; ++i) {
        uint16_t speciesId = requested[i];
        if (!cachedSpeciesFor(speciesId, false) && !knownMissingFile(speciesId)) {
            ready = false;
            break;
        }
    }
    if (loadAttempts > 0) {
        gStats.lastReloadMs = Platform::clock().millis() - start;
        Platform::logf(
            "[PokemonSprites] dynamic lru requested=%u evicted=%u loaded=%u ready=%u ms=%u\n",
            requestedCount, evicted, loadAttempts, ready ? 1 : 0,
            gStats.lastReloadMs);
    }
    gStats.freePsram = Platform::memory().externalFree();
    return ready;
}

void setDynamicSceneSpecies(const uint16_t* speciesIds, uint8_t count) {
    memset(gSceneSpecies, 0, sizeof(gSceneSpecies));
    gSceneSpeciesCount = 0;
    if (!speciesIds) count = 0;
    if (count > SCENE_SPECIES_CAP) count = SCENE_SPECIES_CAP;
    for (uint8_t i = 0; i < count; ++i) {
        uint16_t speciesId = speciesIds[i];
        if (speciesId == 0 ||
            containsSpecies(gSceneSpecies, gSceneSpeciesCount, speciesId)) {
            continue;
        }
        gSceneSpecies[gSceneSpeciesCount++] = speciesId;
        CachedSpecies* cached = cachedSpeciesFor(speciesId, false);
        if (cached) touchEntry(*cached);
    }
}

void setPinnedDynamicSpecies(const uint16_t* speciesIds, uint8_t count) {
    if (!speciesIds) count = 0;
    if (count > EXPLORE_PINNED_CACHE_CAP) {
        count = EXPLORE_PINNED_CACHE_CAP;
    }

    uint16_t next[EXPLORE_PINNED_CACHE_CAP] = {};
    uint8_t nextCount = 0;
    for (uint8_t i = 0; i < count; ++i) {
        uint16_t speciesId = speciesIds[i];
        if (speciesId == 0 ||
            containsSpecies(next, nextCount, speciesId)) {
            continue;
        }
        next[nextCount++] = speciesId;
    }

    bool changed = nextCount != gPinnedSpeciesCount;
    if (!changed) {
        for (uint8_t i = 0; i < nextCount; ++i) {
            if (!containsSpecies(
                    gPinnedSpecies, gPinnedSpeciesCount, next[i])) {
                changed = true;
                break;
            }
        }
    }
    if (!changed) return;

    uint16_t previous[EXPLORE_PINNED_CACHE_CAP] = {};
    uint8_t previousCount = gPinnedSpeciesCount;
    memcpy(previous, gPinnedSpecies, sizeof(previous));
    memcpy(gPinnedSpecies, next, sizeof(gPinnedSpecies));
    gPinnedSpeciesCount = nextCount;

    uint8_t released = 0;
    for (uint8_t i = TEAM_CACHE_CAP; i < CACHE_CAP; ++i) {
        uint16_t speciesId = gCache[i].speciesId;
        if (speciesId == 0 ||
            !containsSpecies(previous, previousCount, speciesId) ||
            containsSpecies(gPinnedSpecies, gPinnedSpeciesCount, speciesId) ||
            containsSpecies(gSceneSpecies, gSceneSpeciesCount, speciesId)) {
            continue;
        }
        releaseEntry(gCache[i]);
        ++released;
    }
    for (uint8_t i = 0; i < gPinnedSpeciesCount; ++i) {
        CachedSpecies* cached =
            cachedSpeciesFor(gPinnedSpecies[i], false);
        if (cached) touchEntry(*cached);
    }
    gStats.freePsram = Platform::memory().externalFree();
    Platform::logf(
        "[PokemonSprites] pinned update species=%u released=%u cached=%u decoded=%u free=%u\n",
        gPinnedSpeciesCount, released, gStats.cachedSpecies,
        gStats.decodedBytes, gStats.freePsram);
}

void setDynamicLoadingEnabled(bool enabled) {
    gDynamicLoadingEnabled = enabled;
}

void beginRenderFrame() {
    memset(gFrameMissing, 0, sizeof(gFrameMissing));
    refreshMissingStats();
}

const SpriteCacheStats& cacheStats() {
    return gStats;
}

bool drawFrame(const SpriteFrame* frame, int x, int y, bool flipX) {
    if (!frame) return false;

    uint8_t width = FlashStorage::readByte(&frame->width);
    uint8_t height = FlashStorage::readByte(&frame->height);
    uint32_t offset = FlashStorage::readDword(&frame->offset);
    uint32_t length = FlashStorage::readDword(&frame->length);
    if (width == 0 || height == 0 || length == 0) return false;

    uint8_t format = FlashStorage::readByte(&frame->format);
    uint8_t source = FlashStorage::readByte(&frame->source);
    if (source != SPRITE_SOURCE_FILE_BLOCK) return false;

    uint16_t speciesId = FlashStorage::readWord(&frame->speciesId);
    CachedSpecies* cached = cachedSpeciesFor(speciesId);
    if (!cached || offset + length > cached->rleWords) return false;
    const uint16_t* rle = cached->data;
    const uint16_t* palettes = cached->palettes;

    if (format == static_cast<uint8_t>(SpriteFormat::INDEXED4_RLE)) {
        uint32_t paletteOffset = FlashStorage::readDword(&frame->paletteOffset);
        uint8_t paletteSize = FlashStorage::readByte(&frame->paletteSize);
        if (paletteOffset + paletteSize > cached->paletteWords) return false;
        PixelRenderer::drawIndexed4Rle(
            x, y, width, height, rle, offset, length, palettes,
            paletteOffset,
            paletteSize,
            flipX);
        return true;
    }

    PixelRenderer::drawRgb565Rle(x, y, width, height, rle, offset, length, flipX);
    return true;
}

bool drawFrameSilhouette(const SpriteFrame* frame, int x, int y,
                         uint16_t color, bool flipX) {
    if (!frame) return false;

    uint8_t width = FlashStorage::readByte(&frame->width);
    uint8_t height = FlashStorage::readByte(&frame->height);
    uint32_t offset = FlashStorage::readDword(&frame->offset);
    uint32_t length = FlashStorage::readDword(&frame->length);
    if (width == 0 || height == 0 || length == 0) return false;

    uint8_t format = FlashStorage::readByte(&frame->format);
    uint8_t source = FlashStorage::readByte(&frame->source);
    if (source != SPRITE_SOURCE_FILE_BLOCK) return false;

    uint16_t speciesId = FlashStorage::readWord(&frame->speciesId);
    CachedSpecies* cached = cachedSpeciesFor(speciesId);
    if (!cached || offset + length > cached->rleWords) return false;

    if (format == static_cast<uint8_t>(SpriteFormat::INDEXED4_RLE)) {
        PixelRenderer::drawIndexed4RleSolid(
            x, y, width, height, cached->data, offset, length, color, flipX);
        return true;
    }
    PixelRenderer::drawRgb565RleSolid(
        x, y, width, height, cached->data, offset, length, color, flipX);
    return true;
}

bool drawFrameScaled(const SpriteFrame* frame, int x, int y, float scale, bool flipX) {
    if (!frame) return false;
    if (scale == 1.0f) return drawFrame(frame, x, y, flipX);

    uint8_t width = FlashStorage::readByte(&frame->width);
    uint8_t height = FlashStorage::readByte(&frame->height);
    uint32_t offset = FlashStorage::readDword(&frame->offset);
    uint32_t length = FlashStorage::readDword(&frame->length);
    if (width == 0 || height == 0 || length == 0 || scale <= 0.0f) return false;

    uint8_t format = FlashStorage::readByte(&frame->format);
    uint8_t source = FlashStorage::readByte(&frame->source);
    if (source != SPRITE_SOURCE_FILE_BLOCK) return false;

    uint16_t speciesId = FlashStorage::readWord(&frame->speciesId);
    CachedSpecies* cached = cachedSpeciesFor(speciesId);
    if (!cached || offset + length > cached->rleWords) return false;
    const uint16_t* rle = cached->data;
    const uint16_t* palettes = cached->palettes;

    if (format == static_cast<uint8_t>(SpriteFormat::INDEXED4_RLE)) {
        uint32_t paletteOffset = FlashStorage::readDword(&frame->paletteOffset);
        uint8_t paletteSize = FlashStorage::readByte(&frame->paletteSize);
        if (paletteOffset + paletteSize > cached->paletteWords) return false;
        PixelRenderer::drawIndexed4RleScaled(
            x, y, width, height, rle, offset, length, palettes,
            paletteOffset,
            paletteSize,
            scale,
            flipX);
        return true;
    }

    PixelRenderer::drawRgb565RleScaled(x, y, width, height, rle, offset, length, scale, flipX);
    return true;
}

}  // namespace PokemonSprites
