#!/usr/bin/env python3
"""Compile ImageGen contact icons into small tintable firmware bitmaps."""

from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "origin_asset/generated/contact_icons"
OUTPUT = ROOT / "firmware/amoled_1_8_v1/main/ui/ContactIcons.h"
NAMES = ("status", "invite", "delete")
SIZE = 40


def bitmap(path: Path) -> list[int]:
    alpha = Image.open(path).convert("RGBA").getchannel("A")
    bounds = alpha.point(lambda value: 255 if value >= 160 else 0).getbbox()
    if bounds is None:
        raise ValueError(f"empty icon: {path}")
    side = max(bounds[2] - bounds[0], bounds[3] - bounds[1])
    center_x = (bounds[0] + bounds[2]) / 2
    center_y = (bounds[1] + bounds[3]) / 2
    # The source PNGs have generous transparent margins; keep only a thin
    # safety border around visible ink in the firmware bitmap.
    padding = side * 0.54
    alpha = alpha.crop((round(center_x - padding), round(center_y - padding),
                        round(center_x + padding), round(center_y + padding)))
    alpha = alpha.resize((SIZE, SIZE), Image.Resampling.LANCZOS)
    pixels = [alpha.getpixel((x, y)) >= 150
              for y in range(SIZE) for x in range(SIZE)]
    if sum(pixels) < SIZE * 2:
        raise ValueError(f"icon too sparse at {SIZE}px: {path}")
    return [sum(1 << (7 - bit) for bit in range(8)
                if pixels[start + bit])
            for start in range(0, SIZE * SIZE, 8)]


def generate() -> str:
    rows = []
    for name in NAMES:
        values = bitmap(SOURCE / f"{name}.png")
        rows.append("    {\n" + "\n".join(
            "        " + ", ".join(f"0x{value:02x}" for value in values[i:i + 14]) + ","
            for i in range(0, len(values), 14)) + "\n    },")
    return """// Generated by tools/generate_contact_icons.py from ImageGen source PNGs.
#pragma once

#include <cstdint>
#include "presentation/Canvas565.h"

namespace AmoledV1::ContactIcons {
enum class Kind : uint8_t { STATUS, INVITE, DELETE };
inline constexpr int SIZE = """ + str(SIZE) + """;
inline constexpr uint8_t PIXELS[][SIZE * SIZE / 8] = {
""" + "\n".join(rows) + """
};

inline void draw(Canvas565& canvas, Kind kind, int x, int y, uint16_t color) {
    const auto& data = PIXELS[static_cast<uint8_t>(kind)];
    for (int row = 0; row < SIZE; ++row) {
        for (int column = 0; column < SIZE; ++column) {
            const int pixel = row * SIZE + column;
            if (data[pixel / 8] & (0x80U >> (pixel % 8))) {
                canvas.drawPixel(x + column, y + row, color);
            }
        }
    }
}
}  // namespace AmoledV1::ContactIcons
"""


if __name__ == "__main__":
    OUTPUT.write_text(generate(), encoding="utf-8")
